language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - pytest
dist: bionic  # As of 6 June 2020, Xenial was the default and it does not support a new enough SQLite for the project.

