[tool.poetry]
name = "astroramjet"
version = "0.7.0"
description = ""
authors = ["Greg Olmschenk <greg@olmschenk.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
pymc3="^*"
retrying="*"
tenacity="*"
bokeh="*"
scipy="*"
astroquery="*"
astropy="*"
pandas="*"
tornado="*"
pathos="*"
tensorflow="^2.4.0"
exoplanet="*"
peewee="*"
requests="*"
numpy="1.21.6"
matplotlib="*"
pytest="*"
pyarrow="*"
pytest-asyncio="*"
wandb="*"
plotly="*"
beautifulsoup4="*"
setuptools="*"
"backports.strenum"="*"
lightkurve="*"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
